language: python
python:
  - "3.6"      # current default Python on Travis CI
#  - "3.7"
#  - "3.8"

before_install:
  - pip install poetry coveralls

install:
  - poetry install -E xlsxwriter

# command to run tests
script:
  - pytest --cov

after_success:
  - coveralls
